metrics:
metrics:
    # Set flag to evaluate model weights; if False, then final updated model will be evaluated
    use_callback: False
    # if use_callback: True, choose the training cycle for the evaluation. Can be 'cycle1', 'cycle2', ...
    saved_training_cycle: cycle2

  # Fill compute_metrics_only if use_train_params: False  
  compute_metrics_only_params:
    # Name of model
    model: poly
    # Set flag to evaluate model weights; if False, then final updated model will be evaluated
    use_callback: False
    # if use_callback: True, choose the training cycle for the evaluation. Can be 'cycle1', 'cycle2', ...
    saved_training_cycle: cycle2
    # if use_train_params: False, provide path to saved model checkpoints.
    chkp_save_path: checkpoint
 # Type of saved model to use for the evaluation. Can be 'final' for a full model, 'checkpoint' for model weights or 'external' for a different model not saved under the same base_id as the current one.
    # SED intepolation points per bin
    sed_interp_pts_per_bin: 0

    # SED extrapolate 
    sed_extrapolate: True
    
    # SED interpolate kind
    sed_interp_kind: linear

    # Standard deviation of the multiplicative SED Gaussian noise.
    sed_sigma: 0

  ground_truth_model:
    model_params:
      #Model used as ground truth for the evaluation. Options are: 'poly', 'physical'.
      model: poly 
      # Evaluation parameters
      # Zernike polynomial modes to use on the ground truth model parametric part.
      n_zernikes: 45
      #Number of bins used for the ground truth model poly PSF generation
      n_bins_lda: 20

  metrics_hparams:
    # Batch size to use for the evaluation.
    eval_batch_size: 16
    #Save RMS error for each super resolved PSF in the test dataset in addition to the mean across the FOV."
    opt_stars_rel_pix_rmse: False
    #Evaluate the monchromatic RMSE metric.
    eval_mono_metric_rmse: True
    #Evaluate the OPD RMSE metric.
    eval_opd_metric_rmse: True
    #Evaluate the super-resolution and the shape RMSE metrics for the train dataset.
    eval_train_shape_sr_metric_rmse: True
    ## Specific parameters
    # Parameter for the l2 loss of the OPD.
    l2_param: 0.
  

