plotting_params:
  # Specify path to model metrics output
  metrics_output_path: /Users/jenniferpollack/Projects/jp272790/
  # List of metrics dir to compare or provide a file containing a list
  metrics_dir: 
    - wf-outputs-202306021300
    - wf-outputs-202305301123
  #Name of Trained Model Metrics Config file
  metrics_config: metrics_config.yaml
  # Plot parameter. Training star number of the different models evaluated.
  star_numbers: 200